/**
 * Digital Asset Links — required for TWA (Trusted Web Activity) verification.
 *
 * Chrome validates this endpoint to confirm the Android app at `package_name`
 * is allowed to open madbekaapp.co.il in a TWA without showing the URL bar.
 *
 * TODO: Replace "REPLACE_WITH_FINGERPRINT_FROM_PLAY_CONSOLE" with the real
 * SHA-256 fingerprint from the keystore generated by PWABuilder / Play Console.
 * The fingerprint looks like: "AB:CD:EF:01:23:..." (32 colon-separated hex pairs).
 */

const assetLinks = [
  {
    relation: ["delegate_permission/common.handle_all_urls"],
    target: {
      namespace: "android_app",
      package_name: "il.co.madbekaapp.twa",
      sha256_cert_fingerprints: [
        "REPLACE_WITH_FINGERPRINT_FROM_PLAY_CONSOLE",
      ],
    },
  },
];

export async function GET() {
  return new Response(JSON.stringify(assetLinks, null, 2), {
    headers: {
      "Content-Type": "application/json",
      // Cache for 1 day — TWA verification doesn't need to be real-time.
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=3600",
    },
  });
}
