"use client";

import { useEffect, useState } from "react";

/**
 * In-app splash screen. Plays a ~2.5s branded animation (M drawn in with a
 * brush, then "Madbeka" fades in below) on the very first paint of each
 * session, then fades away to reveal the real app.
 *
 * Why in-app and not the native Android splash?
 *   The OS-level PWA splash (auto-generated by Chrome from manifest icon +
 *   background_color) is static — Chrome gives us no hook to animate it.
 *   We render a second splash inside the React tree that picks up exactly
 *   where the OS splash leaves off: same white background, same "M +
 *   Madbeka" composition. The hand-off is invisible to the user.
 *
 * Session-scoped so returning from Lemon Squeezy checkout (same tab, same
 * sessionStorage) does NOT re-trigger the animation — nobody wants a 2.5s
 * delay between paying and seeing "תודה על הרכישה".
 */

// Enough for the eye to register "M → Madbeka → done" without feeling slow.
// Anything >3s starts to feel like a real launch screen (Instagram-tier
// polish, but also Instagram-tier annoyance on repeat launches — hence
// sessionStorage guard).
const TOTAL_MS = 2500;
const FADE_MS = 320;

const SESSION_KEY = "madbeka:splash-shown";

export function SplashScreen() {
  // `mounted` controls whether the overlay is in the DOM at all.
  // `fading` triggers the final opacity transition before unmount.
  // Default to `false` on the server so SSR markup matches the fast path
  // (post-animation user) — hydration then decides whether to show it.
  const [mounted, setMounted] = useState(false);
  const [fading, setFading] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;

    // Respect user motion preferences — if they've asked for reduced
    // motion, skip the splash entirely. A 2.5s animated overlay is
    // explicitly the kind of thing that flag is for.
    const prefersReduced = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;
    if (prefersReduced) return;

    // Show once per tab session. Navigations within the app and the
    // Lemon Squeezy round-trip all preserve sessionStorage.
    if (sessionStorage.getItem(SESSION_KEY)) return;
    sessionStorage.setItem(SESSION_KEY, "1");

    // React 19's `set-state-in-effect` rule: schedule state updates in a
    // microtask rather than synchronously inside the effect body.
    let cancelled = false;
    let fadeTimer: number | null = null;
    let unmountTimer: number | null = null;

    (async () => {
      await Promise.resolve();
      if (cancelled) return;
      setMounted(true);
      fadeTimer = window.setTimeout(() => {
        if (!cancelled) setFading(true);
      }, TOTAL_MS - FADE_MS);
      unmountTimer = window.setTimeout(() => {
        if (!cancelled) setMounted(false);
      }, TOTAL_MS);
    })();

    return () => {
      cancelled = true;
      if (fadeTimer !== null) window.clearTimeout(fadeTimer);
      if (unmountTimer !== null) window.clearTimeout(unmountTimer);
    };
  }, []);

  if (!mounted) return null;

  return (
    <div
      aria-hidden="true"
      // pointer-events-none on the final fade so the underlying UI becomes
      // interactive a touch before the splash is fully gone.
      className={
        "fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-white transition-opacity duration-300 ease-out " +
        (fading ? "opacity-0 pointer-events-none" : "opacity-100")
      }
      style={{
        // Use the same font variable the Google Font loader registered in
        // layout.tsx. Fallback to generic cursive if the web font hasn't
        // loaded yet — ugly but only for a flash, and the clip-path reveal
        // still "works" on a fallback face.
        fontFamily:
          "var(--font-rubik-wet-paint), 'Rubik Wet Paint', cursive",
      }}
    >
      {/*
        The "M" — drawn in left-to-right via a clip-path animation. With a
        brush/ink font this reads as the letter being painted on, which is
        exactly the handwritten feel we're after without having to ship a
        bespoke SVG path.
      */}
      <div
        style={{
          fontSize: "min(55vw, 44vh)",
          lineHeight: 1,
          color: "#000000",
          animation: "madbeka-brush-reveal 1100ms cubic-bezier(0.2, 0.7, 0.2, 1) both",
          // Start hidden (inset right = 100%), animation sweeps it to 0.
          clipPath: "inset(0 100% 0 0)",
        }}
      >
        M
      </div>

      {/*
        The wordmark — fades up from a small offset so it "lands" under the
        M right around the time the brush stroke finishes. 850ms delay ≈
        75% through the M reveal, which feels unified rather than sequential.
      */}
      <div
        style={{
          fontSize: "min(12vw, 9vh)",
          lineHeight: 1,
          color: "#000000",
          marginTop: "0.25em",
          opacity: 0,
          transform: "translateY(10px)",
          animation:
            "madbeka-word-fade 700ms cubic-bezier(0.2, 0.7, 0.2, 1) 850ms both",
        }}
      >
        Madbeka
      </div>

      {/* Scoped keyframes — inline so we don't have to touch globals.css for
          a component that only this file uses. */}
      <style>{`
        @keyframes madbeka-brush-reveal {
          0%   { clip-path: inset(0 100% 0 0); }
          100% { clip-path: inset(0 0% 0 0); }
        }
        @keyframes madbeka-word-fade {
          0%   { opacity: 0; transform: translateY(10px); }
          100% { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}
